# Generated by Django 5.0 on 2023-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='readings/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_at', models.DateTimeField(null=True, blank=True)),
                ('parse_error', models.TextField(null=True, blank=True)),
            ],
        ),
    ]
