# Generated by Django 5.0 on 2023-12-18 15:16


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE sensor_reading (
                timestamp TIMESTAMP NOT NULL,
                sensor_name TEXT NOT NULL,
                reading FLOAT NOT NULL
            );
            SELECT create_hypertable('sensor_reading', 'timestamp');
            """,
            reverse_sql="""
                DROP TABLE sensor_reading;
            """
        ),
    ]
